### ISSUE TITLE
seems several srcfiles are missing in this repo? 

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [GT-SALT/SUBS#1]
Hello, Jingfeng.
Thanks a lot for both of your work and your opening-source code
I met up with some problems when trying to reproduce your work (SUBS), 
More specifically, I was trying to reproduce the result of BART(w. gold trees) on GeoQuery task, query split.
Following ReadMe.txt, I enter the command 'bash new_aug_query_gold_span_logic_bart_large.sh'. 
However, I find it seems that several source files are not included in this repo...
e.g., '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/encoder.json';
'/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/vocab.bpe';
and many other files...
![image](https://user-images.githubusercontent.com/60833943/188183885-aa9f1752-fcda-4aec-9900-81e157ead39b.png)

Could you plz make these files available ?   
thank u for your reply !!

**Comment by Zhaoyi-Li21** [comment]
besides, I ran through the codes with LSTM-parser in OpenMT (following the Readme.txt, I entered the command 'bash new_aug_query_induce_logic_copy.sh'). however I got the best result on testing set is **0.6917** (the best performance 0.6917 appeared on **checkpoint- step = 8000,8500,9000**, and when checkpoint-step==9500, the performance would drop to 0.6798, this also implied that step==9500, model was overfitting, and step==8000,8500,9000, model was in its best state(0.6917)...), the results reported in the paper 'SUBS' for this value are supposed to be **0.72**. 
Are there any factors contributing to this difference?
Thanks for replying this !

**Comment by JingfengYang** [comment]
> Hello, Jingfeng. Thanks a lot for both of your work and your opening-source code I met up with some problems when trying to reproduce your work (SUBS), More specifically, I was trying to reproduce the result of BART(w. gold trees) on GeoQuery task, query split. Following ReadMe.txt, I enter the command 'bash new_aug_query_gold_span_logic_bart_large.sh'. However, I find it seems that several source files are not included in this repo... e.g., '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/encoder.json'; '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/vocab.bpe'; and many other files... ![image](https://user-images.githubusercontent.com/60833943/188183885-aa9f1752-fcda-4aec-9900-81e157ead39b.png)
> 
> Could you plz make these files available ? thank u for your reply !!

Hi, you need to download those missing files from https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md [bart.large.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz) as instructed by the official BART libarary.

**Comment by JingfengYang** [comment]
> > Hello, Jingfeng. Thanks a lot for both of your work and your opening-source code I met up with some problems when trying to reproduce your work (SUBS), More specifically, I was trying to reproduce the result of BART(w. gold trees) on GeoQuery task, query split. Following ReadMe.txt, I enter the command 'bash new_aug_query_gold_span_logic_bart_large.sh'. However, I find it seems that several source files are not included in this repo... e.g., '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/encoder.json'; '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/vocab.bpe'; and many other files... ![image](https://user-images.githubusercontent.com/60833943/188183885-aa9f1752-fcda-4aec-9900-81e157ead39b.png)
> > Could you plz make these files available ? thank u for your reply !!
> 
> Hi, you need to download those missing files from https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md [bart.large.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz) as instructed by the official BART libarary.

or [bart.base.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.base.tar.gz) for BART-base. But our results are from BART-Large.

**Comment by Zhaoyi-Li21** [comment]
> > > Hello, Jingfeng. Thanks a lot for both of your work and your opening-source code I met up with some problems when trying to reproduce your work (SUBS), More specifically, I was trying to reproduce the result of BART(w. gold trees) on GeoQuery task, query split. Following ReadMe.txt, I enter the command 'bash new_aug_query_gold_span_logic_bart_large.sh'. However, I find it seems that several source files are not included in this repo... e.g., '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/encoder.json'; '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/vocab.bpe'; and many other files... ![image](https://user-images.githubusercontent.com/60833943/188183885-aa9f1752-fcda-4aec-9900-81e157ead39b.png)
> > > Could you plz make these files available ? thank u for your reply !!
> > 
> > 
> > Hi, you need to download those missing files from https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md [bart.large.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz) as instructed by the official BART libarary.
> 
> or [bart.base.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.base.tar.gz) for BART-base. But our results are from BART-Large.

Hi, Thanks a lot for answering this, Besides I found some missing files in the https://github.com/jonathanherzig/span-based-sp .
Anyway now I can let the program run through ：)

**Comment by Zhaoyi-Li21** [comment]
> > > Hello, Jingfeng. Thanks a lot for both of your work and your opening-source code I met up with some problems when trying to reproduce your work (SUBS), More specifically, I was trying to reproduce the result of BART(w. gold trees) on GeoQuery task, query split. Following ReadMe.txt, I enter the command 'bash new_aug_query_gold_span_logic_bart_large.sh'. However, I find it seems that several source files are not included in this repo... e.g., '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/encoder.json'; '/home/ec2-user/quic-efs/user/jingfe/util_files/bart.base/vocab.bpe'; and many other files... ![image](https://user-images.githubusercontent.com/60833943/188183885-aa9f1752-fcda-4aec-9900-81e157ead39b.png)
> > > Could you plz make these files available ? thank u for your reply !!
> > 
> > 
> > Hi, you need to download those missing files from https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md [bart.large.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz) as instructed by the official BART libarary.
> 
> or [bart.base.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/bart.base.tar.gz) for BART-base. But our results are from BART-Large.

But I have not figured out why there is a mismatch on LSTM'result between the results(**0.6917**) which I reproduced 
(with the command 'bash new_aug_query_induce_logic_copy.sh')
and the reported results in the original paper(**0.72**) (corresponding to 'LSTM + SUBS(induced trees) on Query split').

**Comment by Zhaoyi-Li21** [comment]
Hi, Jingfeng, Sorry to bother you again, Seems I still can not find ''/home/ec2-user/quic-efs/user/jingfe/sem_parses/my_code/semantic_parsing.py" from anywhere... 
![image](https://user-images.githubusercontent.com/60833943/188538394-b7dc9ef1-2f77-4037-b79f-137ea2676819.png)
(in bash new_aug_query_gold_span_logic_bart_large.sh)
So could you please provide 'semantic_parsing.py' ?
Thanks for your reply!

**Comment by JingfengYang** [comment]
Hi sorry for late response and missing that file. I uploaded it here https://github.com/SALT-NLP/SUBS/blob/main/semantic_parsing.py

**Comment by Zhaoyi-Li21** [comment]
Hi, nevermind, thanks for reply and providing 'semantic_parsing.py'. However, I met up with another problem when running 'semantic_parsing.py'. The detailed description is below...
![image](https://user-images.githubusercontent.com/60833943/189396961-86f7157b-f37b-4848-a5b5-50a8382f5248.png)
line 4 'from constraint import build_trie, build_partial_trie'. **Is the 'constraint' package here meaning 'python-constraint'** or **another missing package made by the authors**?  I try to use 'pip install python-constraint' to install constraint package, but the program reported a bug ' **ImportError: cannot import name 'build_trie' from 'constraint'** ', I also check the constraint package and seemingly the constraint package does not contains a function named 'build_trie' or 'build_partial_trie'...
Could you please help me make it to run through the 'semantic_parsing.py' ?

**Comment by Joeylee-rio** [comment]
> Hi, nevermind, thanks for reply and providing 'semantic_parsing.py'. However, I met up with another problem when running 'semantic_parsing.py'. The detailed description is below...
> ![image](https://user-images.githubusercontent.com/60833943/189396961-86f7157b-f37b-4848-a5b5-50a8382f5248.png)
> line 4 'from constraint import build_trie, build_partial_trie'. **Is the 'constraint' package here meaning 'python-constraint'** or **another missing package made by the authors**? I try to use 'pip install python-constraint' to install constraint package, but the program reported a bug ' **ImportError: cannot import name 'build_trie' from 'constraint'** ', I also check the constraint package and seemingly the constraint package does not contains a function named 'build_trie' or 'build_partial_trie'...
> Could you please help me make it to run through the 'semantic_parsing.py' ?

Hi, nevermind, thanks for reply and providing 'semantic_parsing.py'. However, I met up with another problem when running 'semantic_parsing.py'. The detailed description is below...
![image](https://user-images.githubusercontent.com/60833943/189398776-4b44df41-5cc8-40a3-a610-67b08fc7957a.png)

line 4 'from constraint import build_trie, build_partial_trie'. Is the 'constraint' package here meaning 'python-constraint' or another missing package made by the authors? I try to use 'pip install python-constraint' to install constraint package, but the program reported a bug ' ImportError: cannot import name 'build_trie' from 'constraint' ', I also check the constraint package and seemingly the constraint package does not contains a function named 'build_trie' or 'build_partial_trie'...
Could you please help me make it to run through the 'semantic_parsing.py' ?

**Comment by Joeylee-rio** [comment]
> Hi, nevermind, thanks for reply and providing 'semantic_parsing.py'. However, I met up with another problem when running 'semantic_parsing.py'. The detailed description is below...
> ![image](https://user-images.githubusercontent.com/60833943/189396961-86f7157b-f37b-4848-a5b5-50a8382f5248.png)
> line 4 'from constraint import build_trie, build_partial_trie'. **Is the 'constraint' package here meaning 'python-constraint'** or **another missing package made by the authors**? I try to use 'pip install python-constraint' to install constraint package, but the program reported a bug ' **ImportError: cannot import name 'build_trie' from 'constraint'** ', I also check the constraint package and seemingly the constraint package does not contains a function named 'build_trie' or 'build_partial_trie'...
> Could you please help me make it to run through the 'semantic_parsing.py' ?
Hi, nevermind, thanks for reply and providing 'semantic_parsing.py'. However, I met up with another problem when running 'semantic_parsing.py'. The detailed description is below...
![image](https://user-images.githubusercontent.com/60833943/189398960-84fc0168-75e4-4be5-8700-676af771bb68.png)

line 4 'from constraint import build_trie, build_partial_trie'. Is the 'constraint' package here meaning 'python-constraint' or another missing package made by the authors? I try to use 'pip install python-constraint' to install constraint package, but the program reported a bug ' ImportError: cannot import name 'build_trie' from 'constraint' ', I also check the constraint package and seemingly the constraint package does not contains a function named 'build_trie' or 'build_partial_trie'...
Could you please help me make it to run through the 'semantic_parsing.py' ?

**Comment by JingfengYang** [comment]
Hi I put it here https://github.com/SALT-NLP/SUBS/blob/main/constraint.py . But I think this module is not used in this project, because we do not use use_prefix_constraints argument in the bash file. This is used in another of my NAACL paper.

**Comment by JingfengYang** [comment]
Also, did you manage to reproduce the results of LSTM-parser?

**Comment by Joeylee-rio** [comment]
> Hi I put it here https://github.com/SALT-NLP/SUBS/blob/main/constraint.py . But I think this module is not used in this project, because we do not use use_prefix_constraints argument in the bash file. This is used in another of my NAACL paper.
yeh, Now I run through the code with bart-arch, Thanks a lot!

**Comment by Zhaoyi-Li21** [comment]
> Hi I put it here https://github.com/SALT-NLP/SUBS/blob/main/constraint.py . But I think this module is not used in this project, because we do not use use_prefix_constraints argument in the bash file. This is used in another of my NAACL paper.

Yeh, Now I manage to run through the code with bart-parser, Thankkkks a lot!

**Comment by Zhaoyi-Li21** [comment]
> Also, did you manage to reproduce the results of LSTM-parser?

Yes, I think I got the best acc performance (**best here means 'manually select the best performance from all of the checkpoints'** )of **73%** with induce trees(**reported : 72%**), and **77%** with gold trees(**reported : 79%**). Detailed reproduction results (acc graphs) are attached below...
My concern now is that 
**the performance seems not that steady... How can we use the development-set-performance to select which checkpoint as our final prediction model?**
![image](https://user-images.githubusercontent.com/60833943/189474084-61796f04-b5ee-44a1-9e96-9ef5e2897c66.png)

**Comment by JingfengYang** [comment]
Hi, I selected several checkpoints with the best dev score, and then chose the best test score among them. I think it's natural to be unstable, considering the limited test data size. Typically, we can also set different random seeds and report the mean and variance.
